services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - metagate-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: metagate_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - metagate-network

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    networks:
      - metagate-network

  nats-monitoring:
    image: natsio/nats-box:latest
    container_name: nats-box
    depends_on:
      - nats
    networks:
      - metagate-network
    command: ["sleep", "infinity"]

volumes:
  postgres_data:

networks:
  metagate-network:
    driver: bridge